name: 03 - package_win

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  package-builds:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile-build-win
          builder: ${{ steps.buildx.outputs.name }}
          tags: pocket-wallet-win-packager:latest
          push: false

      - name: Run image
        id: docker_run
        uses: addnab/docker-run-action@v3
        with:
          image: pocket-wallet-win-packager:latest
          options: -e GITHUB_SHA=${{ github.sha }} -e S3_BUCKET=pocket-wallet-pub -e BUILDS_TOPIC_ARN=arn:aws:sns:us-east-2:059424750518:PocketWallet -e AWS_REGION=us-east-2 -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e NODE_OPTIONS="--max-old-space-size=4096"
          run: yarn run pack-native-win
